[build]
  publish = "_site"
  command = "quarto render"

[build.environment]
  RENV_CONFIG_REPOS_OVERRIDE = "https://cloud.r-project.org"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
